package klondike.controllers;

public enum Action {
    MOVE_FROM_DECK_TO_WASTE,
    MOVE_FROM_WASTE_TO_DECK,
    MOVE_FROM_WASTE_TO_FOUNDATION,
    MOVE_FROM_WASTE_TO_TABLEAU_STACK,
    MOVE_FROM_TABLEAU_STACK_TO_FOUNDATION,
    MOVE_FROM_TABLEAU_STACK_TO_TABLEAU_STACK,
    MOVE_FROM_FOUNDATION_TO_TABLEAU_STACK,
    FLIP_CARD_ON_TABLEAU_STACK,
    EXIT_GAME
}
